[default]
username = ""
password = ""
port = 27017
host = "localhost"
data_path = "../Data/Hands/"
output_path = "../Outputs/"

  [default.sift]
    collection = "img_sift"
    bin_path = "./bin/sift"
    use_opencv = 1

  [default.loader]
    batch_size = 1000

  [default.window]
    win_height = 100
    win_width = 100

  [default.moment]
    collection = "img_moment_2"
    W_Y_1 = 3
    W_U_1 = 0.5
    W_V_1 = 0.5
    W_Y_2 = 3
    W_U_2 = 0.5
    W_V_2 = 0.5
    W_Y_3 = 3
    W_U_3 = 0.5
    W_V_3 = 0.5
