[default]
# Required config to connect to the MongoDB Database
username = ""
password = ""
port = 27017
host = "localhost"
database = "db"
# Path to the dataset
data_path = "../Data/Hands/"
# Path to the output
output_path = "../Outputs/"

  [default.sift]
  # The colletion to store sift data
    collection = "img_sift"
  # Use opencvs implementation of SIFT algorithm or use the binary provided by
  # David Lowe
    use_opencv = 1
    bin_path = "./bin/sift"

  [default.loader]
  # Batch to operate on
    batch_size = 1000

  [default.window]
  # Images are split into windows when calculating Image Moments. The two
  # configuration specifies the dimensions of the window.
    win_height = 100
    win_width = 100

  [default.moment]
  # The colletion to store moments data
    collection = "img_moment_3"
  # Weights used for the calculation of Moment
  # Format is - W_Y_1, W_Y_2, W_Y_3, W_U_1, W_U_2, W_U_3, W_V_1, W_V_2, W_V_3
  # Must be in double format.
    weights = [3.0, 3.0, 3.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  
  [default.images]
  metadata_csv = "../Data/HandInfo.csv"
  metadata_collection = 'metadata'

